### PR TITLE
Add other options to find RichPaths in RichPathView 

### PR DESCRIPTION
**Pull request by AmrElmasry**
Add other ways to find RichPaths : 
- `findFirstRichPath()` This can be useful if the vector has one path, so no need for searching by name and creating iterator for this.
- `findRichPathByIndex(int index)` This can be useful to find the paths in O(1) instead of O(n), This could be messy if the vector has many paths with complex structure, but it could be useful in cases like hamburger icon where the paths can be recognized easily by the index, This method returns null if the index out of bounds instead of throwing exception to match the existent `findRichPathByName` behavior.

I also updated couple of examples in the sample app to use them, and updated the code snippet in the readme file to include them.

### CODE REVIEW

**Comment by tarek360** [comment]
@AmrElmasry I like the idea and it is an easy way to find a path but sometimes vector-drawable has a group or more and every group has a path, paths, group or groups (hierarchy of paths)
for example:

```xml

<vector>

    <group>

        <path />
        <path />

        <group>
            <path  is this in the index 2 ?  />
            <path />
        </group>

        <path or this in the index 2 ?  />

    </group>

    <path what is the index of this path ?  />

</vector>

```

**Comment by AmrElmasry** [comment]
@tarek360 Thanks for your reply :))
I should have added that the provided index should be the flatten index.
So groups and nested groups will be neglected and paths are flattened.
for example : 
```xml
<vector>
    <group>
        <path /> index 0
        <path /> index 1
        <group>
            <path /> index 2
            <path /> index 3
        </group>
        <path /> index 4
    </group>
    <path /> index 5
</vector>
```
I think this is a little more obvious than `outer.getChildAt(index)` example because in the views-viewGroups tree all the nodes in the tree could be returned from `getChildAt`, so you are interested in getting a "child", and this might be ambiguous if the method will return the parent child or traverse to the its children, but in the case of paths-groups you are interested in "path" so it will always traverse until it finds a path and this path will take the next index.

In complicated vectors this might be confusing, but it brings valuable performance optimization, so I think adding it as an option with more documentation would be helpful :))

**Comment by tarek360** [comment]
I agree with you, could you add this hint to the API doc, please?

By the way, I have added a todo list to the readme, if you have more time for another contribution, also any suggestion is highly appreciated.

Thank you.

**Comment by AmrElmasry** [comment]
Documentation has been added.
Sure, I would like to :))
Thanks :)

**Comment by AmrElmasry** [comment]
@tarek360 I noticed that the commits have been removed, is there anything went wrong ?

**Comment by tarek360** [comment]
@AmrElmasry oh sorry it was a mistake, I will get them back.

**Comment by tarek360** [comment]
@AmrElmasry 
I have created new PR from your branch and I have merged it, but unfortunately, Github considers me the commit author, please create new PR and I will merge it.

**Comment by AmrElmasry** [comment]
@tarek360 Ok thanks :))
I have created another one, I think you will need to revert the last 2 commits on the current master before merging.

**Pull request merged**
